using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Node
{

    public bool autoGenerated;
    public Vector3 worldPosition;
    public List<Node> neighbours = new List<Node>();
    
    public Node(Vector3 _worldPos, bool _autoGenerated) {
        autoGenerated = _autoGenerated;
        worldPosition = _worldPos;
    }

    public void addNeighbour(Node _neighbour) {
        neighbours.Add(_neighbour);
    }
}
